# Generated by Django 4.1.7 on 2023-05-02 10:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_alter_registered_credits_alter_registered_points_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rounds',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Started', 'Started'), ('Completed', 'Completed')], default='Pending', max_length=100),
        ),
        migrations.AlterField(
            model_name='rounds',
            name='Time',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 2, 10, 32, 59, 289262, tzinfo=datetime.timezone.utc)),
        ),
    ]
