# Generated by Django 4.2 on 2023-05-02 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_gamerounds_delete_rounds'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamerounds',
            name='Time',
        ),
    ]
