# Generated by Django 4.2 on 2023-05-04 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0009_gamerounds_deduction_games_award_games_deduction'),
    ]

    operations = [
        migrations.CreateModel(
            name='winners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstPlace', models.CharField(blank=True, max_length=100)),
                ('secondPlace', models.CharField(blank=True, max_length=100)),
                ('thirdPlace', models.CharField(blank=True, max_length=100)),
                ('gameId', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='event.games')),
                ('roundId', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='event.gamerounds')),
            ],
        ),
        migrations.AlterField(
            model_name='gamerounds',
            name='Winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='event.winners'),
        ),
    ]
