# Generated by Django 4.2 on 2023-05-04 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0010_winners_alter_gamerounds_winner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='games',
            name='award',
        ),
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstPlace', models.IntegerField(blank=True)),
                ('secondPlace', models.IntegerField(blank=True)),
                ('thirdPlace', models.IntegerField(blank=True)),
                ('gameId', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='event.games')),
            ],
        ),
        migrations.AddField(
            model_name='games',
            name='gameAward',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='event.award'),
        ),
    ]
