# Generated by Django 4.1.7 on 2023-05-02 10:16

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Games',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Registered',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Qrid', models.CharField(max_length=100)),
                ('Name', models.CharField(blank=True, max_length=100)),
                ('Points', models.IntegerField()),
                ('Credits', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Rounds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Time', models.DateTimeField(default=datetime.datetime(2023, 5, 2, 10, 16, 48, 833748, tzinfo=datetime.timezone.utc))),
                ('Winner', models.CharField(max_length=100)),
                ('Game', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='event.games')),
                ('Participants', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.registered')),
            ],
        ),
    ]
