# Generated by Django 4.2 on 2023-05-02 11:29

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_alter_rounds_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='gameRounds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Time', models.DateTimeField(default=datetime.datetime(2023, 5, 2, 11, 29, 3, 965457, tzinfo=datetime.timezone.utc))),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Started', 'Started'), ('Completed', 'Completed')], default='Pending', max_length=100)),
                ('Winner', models.CharField(blank=True, max_length=100)),
                ('Game', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='event.games')),
                ('Participants', models.ManyToManyField(blank=True, to='event.registered')),
            ],
        ),
        migrations.DeleteModel(
            name='Rounds',
        ),
    ]
