# Generated by Django 4.2 on 2023-05-02 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0007_remove_gamerounds_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamerounds',
            name='Game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.games'),
        ),
    ]
